version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # Монтируем исходный код для горячей перезагрузки
      - ./src:/app/src
      - ./gulpfile.js:/app/gulpfile.js
      # Кэшируем node_modules для производительности
      - node_modules_volume:/app/node_modules
    ports:
      # Проброс портов для Browser Sync
      - "3000:3000"
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  node_modules_volume: